package com.rabitah.frontend.controller;

import com.fasterxml.jackson.databind.JsonNode;import com.rabitah.frontend.AppContext;import java.io.File;import java.io.ByteArrayInputStream;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.nio.file.Path;import java.time.Year;import java.util.*;import javafx.animation.*;import javafx.application.Platform;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.scene.input.KeyEvent;import javafx.scene.layout.HBox;import javafx.scene.layout.VBox;import javafx.stage.FileChooser;import javafx.util.Duration;

/** The main desktop workspace.  It deliberately polls chat as a reliable fallback when sockets reconnect. */
public final class ShellController {
 private final AppContext context;private final Map<String,String> postIds=new LinkedHashMap<>(),commentIds=new LinkedHashMap<>(),commentAuthors=new LinkedHashMap<>(),paperIds=new LinkedHashMap<>(),paperFiles=new LinkedHashMap<>(),users=new LinkedHashMap<>(),conversations=new LinkedHashMap<>(),courses=new LinkedHashMap<>(),pendingUsers=new LinkedHashMap<>(),pendingPosts=new LinkedHashMap<>(),pendingPapers=new LinkedHashMap<>();private String conversationId,communityId,replyParentId;private Path selectedPostMedia,selectedChatMedia;private Timeline approvalPolling,chatPolling;private AutoCloseable realtimeSubscription;
 @FXML private Label welcome,feedStatus,postMediaStatus,chatWith,chatStatus,chatAttachmentStatus,communityName,profileDetails,profileInitial,profileName,profilePhotoStatus,replyTarget,paperStatus,approvalSummary,serverLabel;@FXML private javafx.scene.image.ImageView profileImage;@FXML private TextArea postText,noticeBody;@FXML private TextField commentText,noticeTitle,paperTitle,examYear,paperSearch,messageText,decisionReason,chatSearch,communityText;@FXML private ListView<String> feedList,commentList,noticeList,paperList,messageList,communityList,userApprovalList,postApprovalList,paperApprovalList,chatUserList,conversationList;@FXML private ComboBox<String> noticeType,courseBox;@FXML private Button publishNoticeButton,uploadPaperButton;@FXML private Tab approvalsTab;@FXML private TabPane mainTabs;@FXML private VBox noticeComposer;@FXML private HBox communityComposer;
 public ShellController(AppContext context){this.context=context;this.realtimeSubscription=context.approvals().subscribe(()->Platform.runLater(()->{if(messageList!=null){refreshConversations();refreshMessages();loadCommunity();}}));}
 @FXML private void initialize(){
  var u=context.session().current().user();String identity=u.studentId()==null?u.loginId():u.studentId();
  welcome.setText(u.nickname()+" · "+identity);serverLabel.setText("● Connected");profileInitial.setText(u.nickname().isBlank()?"R":u.nickname().substring(0,1).toUpperCase());profileName.setText(u.nickname());
  profileDetails.setText("Student ID  "+value(u.studentId())+"\nDepartment  "+value(u.department())+"\nSection  "+value(u.section())+"   •   Academic year  "+value(u.academicYear())+"\nRole  "+u.role().replace('_',' '));
  context.api().getBytes("profile/photo").whenComplete((bytes,error)->{if(error==null)Platform.runLater(()->{profileImage.setImage(new javafx.scene.image.Image(new java.io.ByteArrayInputStream(bytes)));profileInitial.setVisible(false);});});
  noticeType.getItems().setAll("GENERAL","ACADEMIC","EXAM","EVENT","EMERGENCY");noticeType.setValue("GENERAL");boolean admin=u.role().equals("SYSTEM_ADMIN");publishNoticeButton.setDisable(!admin);noticeComposer.setVisible(admin);noticeComposer.setManaged(admin);if(!admin)mainTabs.getTabs().remove(approvalsTab);
  // A community room is a real class chat: every scoped member can contribute.
  communityComposer.setVisible(u.department()!=null);communityComposer.setManaged(u.department()!=null);
  feedList.getSelectionModel().selectedItemProperty().addListener((o,a,b)->{cancelReply();refreshComments();});chatUserList.getSelectionModel().selectedItemProperty().addListener((o,a,b)->openConversation());conversationList.getSelectionModel().selectedItemProperty().addListener((o,a,b)->openSelectedConversation());
  refreshFeed();refreshNotices();refreshPapers();loadUsers();refreshConversations();if(u.department()!=null)refreshCommunity();else communityName.setText("Community unavailable for this account");
  chatPolling=new Timeline(new KeyFrame(Duration.seconds(3),e->{refreshConversations();refreshMessages();loadCommunity();}));chatPolling.setCycleCount(Timeline.INDEFINITE);chatPolling.play();
  if(admin){refreshApprovals();realtimeSubscription=context.approvals().subscribe(()->Platform.runLater(this::refreshApprovals));approvalPolling=new Timeline(new KeyFrame(Duration.seconds(10),e->refreshApprovals()));approvalPolling.setCycleCount(Timeline.INDEFINITE);approvalPolling.play();}
 }
 @FXML private void refreshFeed(){run(context.api().getJson("posts/feed"),json->{feedList.getItems().clear();postIds.clear();for(JsonNode p:json){String line=p.path("authorNickname").asText()+"  ·  "+relative(p.path("createdAt").asText())+"\n"+p.path("body").asText()+mediaText(p)+"\n♥ "+p.path("likes").asInt()+"    👎 "+p.path("dislikes").asInt()+"    💬 "+p.path("comments").asInt();feedList.getItems().add(line);postIds.put(line,p.path("id").asText());}feedStatus.setText(feedList.getItems().size()+" posts in your feed");});}
 private String mediaText(JsonNode p){return p.path("media").isArray()&&p.path("media").size()>0?"\n📎 "+p.path("media").get(0).path("originalName").asText("Media attached"):"";}
 @FXML private void choosePostMedia(){FileChooser c=new FileChooser();c.setTitle("Choose an image or video");c.getExtensionFilters().add(new FileChooser.ExtensionFilter("Photos & videos","*.png","*.jpg","*.jpeg","*.gif","*.mp4","*.mov","*.webm"));File f=c.showOpenDialog(postText.getScene().getWindow());if(f!=null){selectedPostMedia=f.toPath();postMediaStatus.setText("Ready: "+f.getName());}}
 @FXML private void createPost(){if(postText.getText().isBlank()&&selectedPostMedia==null){feedStatus.setText("Write something or add media first.");return;}var u=context.session().current().user();Map<String,String> request=new LinkedHashMap<>();request.put("body",postText.getText());request.put("department",valueOrEmpty(u.department()));request.put("section",valueOrEmpty(u.section()));request.put("academicYear",valueOrEmpty(u.academicYear()));if(selectedPostMedia!=null){String type=mediaType(selectedPostMedia);run(context.api().uploadFile("posts",request,selectedPostMedia,type),x->postCreated(x));}else run(context.api().postJson("posts",request),this::postCreated);}
 private void postCreated(JsonNode x){postText.clear();selectedPostMedia=null;postMediaStatus.setText("No media selected");feedStatus.setText("PENDING".equals(x.path("status").asText())?"Submitted for review.":"Published to your campus.");refreshFeed();}
 @FXML private void likePost(){react("LIKE");}@FXML private void dislikePost(){react("DISLIKE");}private void react(String type){String id=selected(postIds,feedList);if(id!=null)run(context.api().putJson("posts/"+id+"/reaction",Map.of("type",type)),x->refreshFeed());}
 @FXML private void commentPost(){String id=selected(postIds,feedList);if(id!=null&&!commentText.getText().isBlank()){Map<String,Object> r=new LinkedHashMap<>();r.put("body",commentText.getText());r.put("parentCommentId",replyParentId);run(context.api().postJson("posts/"+id+"/comments",r),x->{commentText.clear();cancelReply();refreshComments();refreshFeed();});}}
 @FXML private void refreshComments(){String postId=selected(postIds,feedList);commentList.getItems().clear();commentIds.clear();commentAuthors.clear();if(postId==null){replyTarget.setText("Select a post to join the discussion");return;}run(context.api().getJson("posts/"+postId+"/comments"),json->{for(JsonNode c:json){String prefix=c.path("parentCommentId").isNull()?"":"    ↳ ";String line=prefix+c.path("authorNickname").asText()+" · "+relative(c.path("createdAt").asText())+"\n"+prefix+c.path("body").asText()+"\n"+prefix+"♥ "+c.path("likes").asInt()+"  👎 "+c.path("dislikes").asInt();commentList.getItems().add(line);commentIds.put(line,c.path("id").asText());commentAuthors.put(line,c.path("authorNickname").asText());}replyTarget.setText(json.isEmpty()?"No comments yet—be first.":"Comments on this post");});}
 @FXML private void replyToComment(){String line=commentList.getSelectionModel().getSelectedItem();String id=commentIds.get(line);if(id!=null){replyParentId=id;replyTarget.setText("Replying to "+commentAuthors.get(line));commentText.requestFocus();}}@FXML private void cancelReply(){replyParentId=null;}
 @FXML private void refreshNotices(){run(context.api().getJson("notices"),json->{noticeList.getItems().clear();for(JsonNode n:json)noticeList.getItems().add("["+n.path("type").asText()+"]  "+n.path("title").asText()+"\n"+n.path("body").asText()+"\nFor "+n.path("department").asText("all students"));});}
 @FXML private void publishNotice(){if(noticeTitle.getText().isBlank()||noticeBody.getText().isBlank())return;run(context.api().postJson("notices",Map.of("title",noticeTitle.getText(),"body",noticeBody.getText(),"type",noticeType.getValue())),x->{noticeTitle.clear();noticeBody.clear();refreshNotices();});}
 @FXML private void refreshPapers(){run(context.api().getJson("question-papers?q="+URLEncoder.encode(paperSearch.getText(),StandardCharsets.UTF_8)),json->{paperList.getItems().clear();paperIds.clear();paperFiles.clear();for(JsonNode p:json){String line=p.path("courseCode").asText()+"  ·  "+p.path("department").asText()+"\n"+p.path("title").asText()+"  ("+p.path("examYear").asInt()+")\nPDF · "+p.path("filename").asText();paperList.getItems().add(line);paperIds.put(line,p.path("id").asText());paperFiles.put(line,safeFilename(p.path("filename").asText("question.pdf")));}paperStatus.setText(json.size()+" curated papers available");});loadCourses();}
 private void loadCourses(){run(context.api().getJson("question-papers/courses"),json->{courses.clear();courseBox.getItems().clear();for(JsonNode c:json){String label=c.path("code").asText()+" — "+c.path("name").asText();courses.put(label,c.path("id").asText());courseBox.getItems().add(label);}});}
 @FXML private void uploadPaper(){if(courseBox.getValue()==null||paperTitle.getText().isBlank())return;FileChooser c=new FileChooser();c.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF files","*.pdf"));File f=c.showOpenDialog(courseBox.getScene().getWindow());if(f==null)return;String year=examYear.getText().isBlank()?String.valueOf(Year.now().getValue()):examYear.getText();run(context.api().uploadPdf("question-papers",Map.of("courseId",courses.get(courseBox.getValue()),"title",paperTitle.getText(),"examYear",year),f.toPath()),x->{paperTitle.clear();paperStatus.setText("PENDING".equals(x.path("status").asText())?"Submitted for review.":"Paper uploaded.");refreshPapers();});}
 @FXML private void downloadPaper(){String line=paperList.getSelectionModel().getSelectedItem();String id=paperIds.get(line);if(id==null){paperStatus.setText("Select a paper first.");return;}FileChooser c=new FileChooser();c.setInitialFileName(paperFiles.get(line));File f=c.showSaveDialog(paperList.getScene().getWindow());if(f!=null)run(context.api().download("question-papers/"+id+"/download",f.toPath()),p->paperStatus.setText("Saved to "+p.getFileName()));}
 private void loadUsers(){run(context.api().getJson("chat/users"),json->{users.clear();for(JsonNode u:json){String label=u.path("nickname").asText()+"\n"+u.path("loginId").asText()+" · "+u.path("department").asText("");users.put(label,u.path("loginId").asText());}filterChatUsers();});}
 @FXML private void searchChatUsers(KeyEvent ignored){filterChatUsers();}private void filterChatUsers(){String q=chatSearch==null?"":chatSearch.getText().toLowerCase();chatUserList.getItems().setAll(users.keySet().stream().filter(x->x.toLowerCase().contains(q)).toList());}
 @FXML private void openConversation(){String id=selected(users,chatUserList);if(id==null)return;run(context.api().postJson("chat/conversations/with/"+id,Map.of()),json->{conversationId=json.path("id").asText();chatWith.setText(json.path("otherNickname").asText());chatStatus.setText("Active now");refreshConversations();refreshMessages();});}
 private void refreshConversations(){run(context.api().getJson("chat/conversations"),json->{String current=conversationId;conversations.clear();conversationList.getItems().clear();for(JsonNode c:json){String line=c.path("otherNickname").asText()+"\n"+c.path("otherLoginId").asText();conversations.put(line,c.path("id").asText());conversationList.getItems().add(line);if(c.path("id").asText().equals(current))conversationList.getSelectionModel().select(line);}});}
 private void openSelectedConversation(){String id=selected(conversations,conversationList);if(id==null||id.equals(conversationId))return;conversationId=id;chatWith.setText(conversationList.getSelectionModel().getSelectedItem().split("\\n")[0]);chatStatus.setText("Conversation refreshed automatically");refreshMessages();}
 private void refreshMessages(){if(conversationId==null)return;run(context.api().getJson("chat/conversations/"+conversationId+"/messages"),json->{messageList.getItems().clear();for(JsonNode m:json){String attachment=m.path("attachmentName").isMissingNode()||m.path("attachmentName").isNull()?"":"\n📎 "+m.path("attachmentName").asText();messageList.getItems().add(m.path("senderNickname").asText()+"  ·  "+relative(m.path("sentAt").asText())+"\n"+m.path("body").asText()+attachment);}if(!json.isEmpty())messageList.scrollTo(json.size()-1);});}
 @FXML private void chooseChatAttachment(){if(conversationId==null){chatStatus.setText("Select a person first.");return;}FileChooser c=new FileChooser();c.setTitle("Choose a photo, video, or file");File f=c.showOpenDialog(messageText.getScene().getWindow());if(f!=null){selectedChatMedia=f.toPath();chatAttachmentStatus.setText("Ready to send: "+f.getName());}}
 @FXML private void sendMessage(){if(conversationId==null||(messageText.getText().isBlank()&&selectedChatMedia==null))return;if(selectedChatMedia!=null)run(context.api().uploadFile("chat/conversations/"+conversationId+"/messages",Map.of("body",messageText.getText()),selectedChatMedia,mediaType(selectedChatMedia)),x->{messageText.clear();selectedChatMedia=null;chatAttachmentStatus.setText("");refreshMessages();refreshConversations();});else run(context.api().postJson("chat/conversations/"+conversationId+"/messages",Map.of("body",messageText.getText())),x->{messageText.clear();refreshMessages();refreshConversations();});}
 @FXML private void refreshCommunity(){run(context.api().getJson("community/rooms/mine"),room->{communityId=room.path("id").asText();communityName.setText(room.path("name").asText());loadCommunity();});}private void loadCommunity(){if(communityId==null)return;run(context.api().getJson("community/rooms/"+communityId+"/messages"),json->{communityList.getItems().clear();for(JsonNode m:json)communityList.getItems().add(m.path("authorNickname").asText()+"  ·  "+relative(m.path("createdAt").asText())+"\n"+m.path("body").asText());});}@FXML private void sendCommunityMessage(){if(communityId==null||communityText.getText().isBlank())return;run(context.api().postJson("community/rooms/"+communityId+"/messages",Map.of("body",communityText.getText())),x->{communityText.clear();loadCommunity();});}
 @FXML private void chooseProfilePhoto(){FileChooser c=new FileChooser();c.setTitle("Choose profile photo");c.getExtensionFilters().add(new FileChooser.ExtensionFilter("Image files","*.png","*.jpg","*.jpeg","*.webp"));File f=c.showOpenDialog(profileInitial.getScene().getWindow());if(f==null)return;run(context.api().uploadFile("profile/photo",Map.of(),f.toPath(),mediaType(f.toPath())),x->{profileImage.setImage(new javafx.scene.image.Image(f.toURI().toString()));profileInitial.setVisible(false);profilePhotoStatus.setText("Profile photo updated successfully.");});}
 @FXML private void refreshApprovals(){refreshApprovalSummary();loadApprovals("users",userApprovalList,pendingUsers,n->n.path("studentId").asText()+" — "+n.path("legalName").asText());loadApprovals("posts",postApprovalList,pendingPosts,n->n.path("authorNickname").asText()+"\n"+n.path("body").asText());loadApprovals("papers",paperApprovalList,pendingPapers,n->n.path("courseCode").asText()+" — "+n.path("title").asText());}private void refreshApprovalSummary(){runApproval(context.api().getJson("admin/approvals/summary"),s->approvalSummary.setText(s.path("users").asInt()+" students · "+s.path("posts").asInt()+" posts · "+s.path("papers").asInt()+" PDFs awaiting review"));}private void loadApprovals(String kind,ListView<String> list,Map<String,String> ids,java.util.function.Function<JsonNode,String> format){runApproval(context.api().getJson("admin/approvals/"+kind),json->{list.getItems().clear();ids.clear();for(JsonNode n:json){String line=format.apply(n);list.getItems().add(line);ids.put(line,n.path("id").asText());}});}
 @FXML private void approveUser(){decide("users",pendingUsers,userApprovalList,"APPROVE");}@FXML private void rejectUser(){decide("users",pendingUsers,userApprovalList,"REJECT");}@FXML private void approvePost(){decide("posts",pendingPosts,postApprovalList,"APPROVE");}@FXML private void rejectPost(){decide("posts",pendingPosts,postApprovalList,"REJECT");}@FXML private void approvePaper(){decide("papers",pendingPapers,paperApprovalList,"APPROVE");}@FXML private void rejectPaper(){decide("papers",pendingPapers,paperApprovalList,"REJECT");}private void decide(String kind,Map<String,String> ids,ListView<String> list,String action){String id=selected(ids,list);if(id==null){approvalSummary.setText("Select a request first.");return;}Map<String,Object> r=new LinkedHashMap<>();r.put("action",action);r.put("reason",decisionReason.getText().isBlank()?null:decisionReason.getText());runApproval(context.api().putJson("admin/approvals/"+kind+"/"+id,r),x->{decisionReason.clear();refreshApprovals();if(kind.equals("posts"))refreshFeed();if(kind.equals("papers"))refreshPapers();});}
 @FXML private void logout(){if(approvalPolling!=null)approvalPolling.stop();if(chatPolling!=null)chatPolling.stop();try{if(realtimeSubscription!=null)realtimeSubscription.close();}catch(Exception ignored){}context.session().clear();context.router().showLogin();}
 private <T> void run(java.util.concurrent.CompletableFuture<T> task,java.util.function.Consumer<T> ok){task.whenComplete((v,e)->Platform.runLater(()->{if(e!=null){feedStatus.setText("Error: "+message(e));}else ok.accept(v);}));}private <T> void runApproval(java.util.concurrent.CompletableFuture<T> task,java.util.function.Consumer<T> ok){task.whenComplete((v,e)->Platform.runLater(()->{if(e!=null)approvalSummary.setText("Error: "+message(e));else ok.accept(v);}));}private String selected(Map<String,String> map,ListView<String> list){return map.get(list.getSelectionModel().getSelectedItem());}private String value(Object v){return v==null?"Not applicable":v.toString();}private String valueOrEmpty(Object v){return v==null?"":v.toString();}private String safeFilename(String n){return n.replaceAll("[\\\\/:*?\"<>|\\r\\n]","_");}private String mediaType(Path p){try{String t=java.nio.file.Files.probeContentType(p);return t==null?"application/octet-stream":t;}catch(Exception e){return "application/octet-stream";}}private String message(Throwable e){Throwable c=e.getCause()==null?e:e.getCause();return c.getMessage()==null?"Request failed":c.getMessage();}private String relative(String raw){return raw==null||raw.isBlank()?"just now":"just now";}
}
