package com.rabitah.backend.profile;

import com.rabitah.backend.common.ApiException;import com.rabitah.backend.security.CurrentUserService;import com.rabitah.backend.storage.MediaStorage;import com.rabitah.backend.user.User;import java.util.*;import org.springframework.http.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;

@RestController @RequestMapping("/api/v1/profile") public final class ProfileController {
 private final JdbcTemplate jdbc;private final CurrentUserService current;private final MediaStorage storage;public ProfileController(JdbcTemplate jdbc,CurrentUserService current,MediaStorage storage){this.jdbc=jdbc;this.current=current;this.storage=storage;}
 @PostMapping(value="/photo",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Map<String,String> photo(@RequestPart MultipartFile file,Authentication auth)throws Exception{User u=current.require(auth);if(file.isEmpty()||file.getContentType()==null||!file.getContentType().toLowerCase().startsWith("image/"))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PHOTO","Please select a PNG, JPG, WEBP, or other image file.");if(file.getSize()>5_000_000)throw new ApiException(HttpStatus.BAD_REQUEST,"PHOTO_TOO_LARGE","Profile photos must be 5 MB or smaller.");String key=storage.save("profiles/"+u.getId(),file);jdbc.update("update users set profile_photo_key=?,updated_at=now() where id=?",key,u.getId());return Map.of("message","Profile photo updated","url","/api/v1/profile/photo");}
 @GetMapping("/photo") public ResponseEntity<byte[]> photo(Authentication auth)throws Exception{User u=current.require(auth);List<String> rows=jdbc.query("select profile_photo_key from users where id=? and profile_photo_key is not null",(rs,n)->rs.getString(1),u.getId());if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"PHOTO_NOT_FOUND","No profile photo yet");return ResponseEntity.ok().contentType(MediaType.APPLICATION_OCTET_STREAM).body(storage.read(rows.getFirst()));}
}
