package com.rabitah.frontend.api;

import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule; import com.rabitah.frontend.session.SessionManager; import java.net.*; import java.net.http.*; import java.nio.file.*; import java.time.Duration; import java.util.*; import java.util.concurrent.*;

public final class ApiClient {
 private final URI base;private final SessionManager session;private final Executor executor;private final HttpClient http;private final ObjectMapper json=new ObjectMapper().registerModule(new JavaTimeModule());
 public ApiClient(URI base,SessionManager session,Executor executor){this.base=base;this.session=session;this.executor=executor;this.http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).executor(executor).build();}
 public <T> CompletableFuture<T> post(String path,Object body,Class<T> type){return jsonRequest(path,"POST",body,type);}public CompletableFuture<JsonNode> getJson(String path){return send(builder(path).GET().build(),JsonNode.class);}public CompletableFuture<JsonNode> postJson(String path,Object body){return jsonRequest(path,"POST",body,JsonNode.class);}public CompletableFuture<JsonNode> putJson(String path,Object body){return jsonRequest(path,"PUT",body,JsonNode.class);}public CompletableFuture<Void> delete(String path){return http.sendAsync(builder(path).DELETE().build(),HttpResponse.BodyHandlers.ofString()).thenApplyAsync(r->{if(r.statusCode()<200||r.statusCode()>=300)throw new ApiClientException(r.statusCode(),message(r.body()));return null;},executor);}
 private <T> CompletableFuture<T> jsonRequest(String path,String method,Object body,Class<T> type){try{return send(builder(path).header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),type);}catch(Exception e){return CompletableFuture.failedFuture(e);}}
 public CompletableFuture<JsonNode> uploadPdf(String path,Map<String,String> fields,Path file){return uploadFile(path,fields,file,"application/pdf");}public CompletableFuture<byte[]> getBytes(String path){return http.sendAsync(builder(path).GET().build(),HttpResponse.BodyHandlers.ofByteArray()).thenApplyAsync(r->{if(r.statusCode()<200||r.statusCode()>=300)throw new ApiClientException(r.statusCode(),"File unavailable");return r.body();},executor);}
 public CompletableFuture<JsonNode> uploadFile(String path,Map<String,String> fields,Path file,String contentType){return uploadMultipart(path,fields,List.of(file),List.of(contentType),"file");}
 /** Sends repeated multipart parts under one name, for example a post's {@code files} attachments. */
 public CompletableFuture<JsonNode> uploadFiles(String path,Map<String,String> fields,List<Path> files){if(files==null||files.isEmpty())return CompletableFuture.failedFuture(new IllegalArgumentException("Choose at least one file."));List<String> types=new ArrayList<>();for(Path file:files)types.add(contentType(file));return uploadMultipart(path,fields,files,types,"files");}
 private CompletableFuture<JsonNode> uploadMultipart(String path,Map<String,String> fields,List<Path> files,List<String> contentTypes,String partName){try{String boundary="Rabitah"+UUID.randomUUID();List<byte[]> parts=new ArrayList<>();for(var e:fields.entrySet())parts.add(("--"+boundary+"\r\nContent-Disposition: form-data; name=\""+e.getKey()+"\"\r\n\r\n"+e.getValue()+"\r\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));for(int i=0;i<files.size();i++){Path file=files.get(i);parts.add(("--"+boundary+"\r\nContent-Disposition: form-data; name=\""+partName+"\"; filename=\""+file.getFileName()+"\"\r\nContent-Type: "+contentTypes.get(i)+"\r\n\r\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));parts.add(Files.readAllBytes(file));parts.add("\r\n".getBytes(java.nio.charset.StandardCharsets.UTF_8));}parts.add(("--"+boundary+"--\r\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));return send(builder(path).timeout(Duration.ofMinutes(5)).header("Content-Type","multipart/form-data; boundary="+boundary).POST(HttpRequest.BodyPublishers.ofByteArrays(parts)).build(),JsonNode.class);}catch(Exception e){return CompletableFuture.failedFuture(e);}}
 private String contentType(Path file){try{String type=Files.probeContentType(file);return type==null||type.isBlank()?"application/octet-stream":type;}catch(Exception ignored){return "application/octet-stream";}}
 public CompletableFuture<Path> download(String path,Path destination){return http.sendAsync(builder(path).GET().build(),HttpResponse.BodyHandlers.ofByteArray()).thenApplyAsync(r->{if(r.statusCode()<200||r.statusCode()>=300)throw new ApiClientException(r.statusCode(),message(new String(r.body(),java.nio.charset.StandardCharsets.UTF_8)));try{Path parent=destination.toAbsolutePath().getParent();if(parent!=null)Files.createDirectories(parent);Files.write(destination,r.body(),StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);return destination;}catch(Exception e){throw new ApiClientException(r.statusCode(),"Could not save the file",e);}},executor);}
 private HttpRequest.Builder builder(String path){var b=HttpRequest.newBuilder(base.resolve(path)).timeout(Duration.ofSeconds(30));if(session.accessToken()!=null)b.header("Authorization","Bearer "+session.accessToken());return b;}private <T> CompletableFuture<T> send(HttpRequest request,Class<T> type){return http.sendAsync(request,HttpResponse.BodyHandlers.ofString()).thenApplyAsync(r->{if(r.statusCode()<200||r.statusCode()>=300)throw new ApiClientException(r.statusCode(),message(r.body()));try{return json.readValue(r.body(),type);}catch(Exception e){throw new ApiClientException(r.statusCode(),"The server returned an unreadable response",e);}},executor);}private String message(String body){try{return json.readTree(body).path("message").asText("Request failed");}catch(Exception e){return "Request failed";}}
 public static final class ApiClientException extends RuntimeException{private final int status;public ApiClientException(int status,String message){super(message);this.status=status;}public ApiClientException(int status,String message,Throwable cause){super(message,cause);this.status=status;}public int status(){return status;}}
}
